postgresql.connection = 'postgres://repl_user@localhost:5432/postgres'
postgresql.password = '...'
#postgresql.publication.name = 'publication_name'
#postgresql.publication.create = false
#postgresql.publication.autodrop = true
#postgresql.replicationslot.name = 'replication_slot_name'
#postgresql.replicationslot.create = true
#postgresql.replicationslot.autodrop = true
#postgresql.snapshot.batchsize = 1000
#postgresql.snapshot.initial = 'always'
#postgresql.transaction.window.enabled = true
#postgresql.transaction.window.timeout = 60
#postgresql.transaction.window.maxsize = 10000

statestorage.type = 'file'
statestorage.file.path = '/tmp/statestorage.dat'

#internal.dispatcher.initialqueuecapacity = 16384
#internal.snapshotter.parallelsim = 5

sink.tombstone = false

#sink.filters.filterName.condition = '''value.op == "u" && value.before.id == 2'''
#sink.filters.filterName.default = true

sink.type = 'stdout'

#sink.type = 'nats'
#sink.nats.address = 'nats://localhost:4222'
#sink.nats.timeout = 5
#sink.nats.authorization = "userinfo"
#sink.nats.userinfo.username = 'publisher'
#sink.nats.userinfo.password = '...'

#sink.type = 'kafka'
#sink.kafka.brokers = ['']
#sink.kafka.sasl.enabled = true
#sink.kafka.sasl.user = '$ConnectionString'
#sink.kafka.sasl.mechanism = 'PLAIN'
#sink.kafka.tls.enabled = true
#sink.kafka.tls.skipverify = true
#sink.kafka.tls.clientauth = 0

#sink.redis.network = 'tcp'
#sink.redis.address = 'localhost:6379'
#sink.redis.password = '...'
#sink.redis.database = 0
#sink.redis.poolsize = 0
#sink.redis.retries.maxattempts = 0
#sink.redis.retries.backoff.min = 8
#sink.redis.retries.backoff.max = 512
#sink.redis.timeouts.dial = 0
#sink.redis.timeouts.read = 0
#sink.redis.timeouts.write = 0
#sink.redis.timeouts.pool = 0
#sink.redis.timeouts.idle = 0
#sink.redis.tls.enabled = false
#sink.redis.tls.skipverify = false
#sink.redis.tls.clientauth = 0

#sink.kinesis.stream.name = 'stream_name'
#sink.kinesis.stream.create = true
#sink.kinesis.stream.shardcount = 10
#sink.kinesis.stream.mode = '...'
#sink.kinesis.aws.region = '...'
#sink.kinesis.aws.endpoint = '...'
#sink.kinesis.aws.accesskeyid = '...'
#sink.kinesis.aws.secretaccesskey = '...'
#sink.kinesis.aws.sessiontoken = '...'

#sink.sqs.queue.url = 'queue_url'
#sink.sqs.aws.region = '...'
#sink.sqs.aws.endpoint = '...'
#sink.sqs.aws.accesskeyid = '...'
#sink.sqs.aws.secretaccesskey = '...'
#sink.sqs.aws.sessiontoken = '...'

#sink.http.url = 'http://localhost:8080'
#sink.http.authentication.type = 'basic'
#sink.http.authentication.basic.username = 'test'
#sink.http.authentication.basic.password = '...'
#sink.http.authentication.header.name = 'x-api-key'
#sink.http.authentication.header.value = '...'
#sink.http.tls.skipverify = false
#sink.http.tls.clientauth = 0

topic.namingstrategy.type = 'debezium'
topic.prefix = 'timescaledb'

timescaledb.hypertables.excludes = ['pgcatalog.*']
timescaledb.hypertables.includes = ['public.test']
timescaledb.events.read = true
timescaledb.events.insert = true
timescaledb.events.update = true
timescaledb.events.delete = true
timescaledb.events.truncate = true
timescaledb.events.message = false #deprecated: see postgresql.events.message
timescaledb.events.compression = false
timescaledb.events.decompression = false

postgresql.tables.excludes = ['pgcatalog.*']
postgresql.tables.includes = ['public.*']
postgresql.events.read = true
postgresql.events.insert = true
postgresql.events.update = true
postgresql.events.delete = true
postgresql.events.truncate = true
postgresql.events.message = false

logging.level = 'info'
logging.outputs.console.enabled = true
logging.outputs.file.enabled = false
logging.outputs.file.path = '/path/to/logfile'
logging.outputs.file.rotate = true
logging.outputs.file.maxsize = '5MB'
logging.outputs.file.maxduration = 600 #seconds
logging.outputs.file.compress = true
logging.loggers.LogicalReplicationResolver.level = 'debug'
logging.loggers.LogicalReplicationResolver.outputs.console.enabled = false

#stats.enabled = true
#stats.port = 8081
#stats.runtime.enabled = true